# Generated by Django 5.0.1 on 2025-11-22 19:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0003_payment_adoptionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('campaign_type', models.CharField(choices=[('emergency', '🚨 Emergency Response'), ('species', '🌳 Species Protection'), ('restoration', '🌲 Forest Restoration'), ('education', '🎓 Community Education'), ('research', '🔬 Research Project')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('funded', 'Fully Funded'), ('ongoing', 'Implementation Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('forest_name', models.CharField(help_text='e.g., Karura Forest', max_length=200)),
                ('forest_area_hectares', models.DecimalField(decimal_places=2, help_text='Total area in hectares', max_digits=10)),
                ('county', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('funding_goal', models.DecimalField(decimal_places=2, help_text='Target amount in KES', max_digits=12)),
                ('current_funding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trees_target', models.IntegerField(help_text='Number of endangered trees to protect')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='campaigns/covers/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('budget_breakdown', models.JSONField(default=dict, help_text='JSON with budget categories and amounts')),
                ('spending_log', models.JSONField(default=list, help_text='Array of spending records')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('rangers', models.ManyToManyField(limit_choices_to={'user_type': 'ranger'}, related_name='assigned_campaigns', to=settings.AUTH_USER_MODEL)),
                ('trees', models.ManyToManyField(blank=True, related_name='campaigns', to='trees.tree')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('community', '🏘️ Community'), ('school', '🎓 School'), ('organization', '🏢 Organization'), ('individual', '👤 Individual Citizen'), ('corporate', '🏭 Corporate Sponsor')], max_length=20)),
                ('role', models.CharField(choices=[('leader', 'Campaign Leader'), ('member', 'Member'), ('sponsor', 'Sponsor'), ('volunteer', 'Volunteer')], default='member', max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='campaigns/logos/')),
                ('total_contributed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_contribution_date', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_contributed', '-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('corporate', 'Corporate Sponsorship')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, help_text='Message from contributor')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='campaigns.campaign')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='campaigns.campaignparticipant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('progress', '📊 Progress Update'), ('milestone', '🎯 Milestone Achieved'), ('photo', '📸 Photo Update'), ('video', '🎥 Video Update'), ('spending', '💰 Spending Report'), ('alert', '🚨 Alert/Issue')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('photos', models.JSONField(default=list, help_text='Array of photo URLs')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('options', models.JSONField(help_text='Array of voting options')),
                ('results', models.JSONField(default=dict, help_text='Vote counts per option')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=200)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaignparticipant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to='campaigns.campaignvote')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', '-created_at'], name='campaigns_c_status_db0aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type', 'status'], name='campaigns_c_campaig_c8f2ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignparticipant',
            unique_together={('campaign', 'user')},
        ),
        migrations.AddIndex(
            model_name='campaigncontribution',
            index=models.Index(fields=['campaign', '-created_at'], name='campaigns_c_campaig_94c715_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncontribution',
            index=models.Index(fields=['status', '-created_at'], name='campaigns_c_status_734717_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together={('vote', 'user')},
        ),
    ]
