# Generated by Django 5.0.1 on 2025-11-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_incidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
