# Generated by Django 5.2.8 on 2025-11-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_adoption', 'First Tree Adopted'), ('five_adoptions', 'Five Trees Adopted'), ('ten_adoptions', 'Ten Trees Adopted'), ('first_report', 'First Report Submitted'), ('ten_reports', 'Ten Reports Submitted'), ('ranger_verified', 'Ranger Verified'), ('tree_saver', 'Tree Saver')], max_length=50)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-earned_date'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.CharField(help_text='Unique identifier for the tree', max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_name', models.CharField(help_text='Forest or area name', max_length=200)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('stressed', 'Stressed'), ('diseased', 'Diseased'), ('critical', 'Critical'), ('deceased', 'Deceased')], default='healthy', max_length=20)),
                ('estimated_age', models.IntegerField(blank=True, help_text='Age in years', null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters', max_digits=5, null=True)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, help_text='Trunk diameter in cm', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_adopted', models.BooleanField(default=False)),
                ('adoption_count', models.IntegerField(default=0)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trees/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the adoption')),
            ],
            options={
                'ordering': ['-adoption_date'],
            },
        ),
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('critically_endangered', 'Critically Endangered'), ('endangered', 'Endangered'), ('vulnerable', 'Vulnerable')], max_length=50)),
                ('native_region', models.CharField(max_length=200)),
                ('characteristics', models.TextField(help_text='Physical characteristics')),
                ('conservation_importance', models.TextField(help_text='Why this species matters')),
                ('threats', models.TextField(help_text='Main threats to this species')),
                ('image', models.ImageField(blank=True, null=True, upload_to='species/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tree Species',
                'ordering': ['name'],
            },
        ),
    ]
