# Generated by Django 5.2.8 on 2025-11-15 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tree',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_trees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treeadoption',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='trees.tree'),
        ),
        migrations.AddField(
            model_name='treeadoption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tree',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='trees.treespecies'),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('user', 'badge_type')},
        ),
        migrations.AlterUniqueTogether(
            name='treeadoption',
            unique_together={('user', 'tree')},
        ),
    ]
