# Generated by Django 5.0.1 on 2025-11-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_forest',
            field=models.CharField(blank=True, help_text='Primary forest area assigned to', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='certification_number',
            field=models.CharField(blank=True, help_text='Official ranger certification ID', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g., Wildlife Protection, Fire Management, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years working as a ranger', null=True),
        ),
    ]
